DROP TABLE IF EXISTS Protocols;
DROP TABLE IF EXISTS Medications;
DROP TABLE IF EXISTS LabResults;
DROP TABLE IF EXISTS Patients;

CREATE TABLE Patients (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    familyname TEXT NOT NULL,
    birthdate TEXT NOT NULL, 
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Protocols (
    patient_id INTEGER PRIMARY KEY,
    dialyzer TEXT,
    access TEXT,
    dialysateFlow TEXT,
    bloodFlow TEXT,
    duration TEXT,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(patient_id) REFERENCES Patients(id) ON DELETE CASCADE
);

CREATE TABLE Medications (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    patient_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    dosage TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(patient_id) REFERENCES Patients(id) ON DELETE CASCADE
);

CREATE TABLE LabResults (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    patient_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    result TEXT NOT NULL, 
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(patient_id) REFERENCES Patients(id) ON DELETE CASCADE
);
